fix: to correct response status code
google/nginx-sxg-module pull request #83
Opened 2020-12-18 17:48 UTC by orisano

I encountered a problem that nginx response status code is 000.
Maybe this problem happened from #62.

I fixed to respond always 200 OK.
question: Is it right to always return 200?

2020-12-19 14:00 UTC, kumagi requested changes
AFAIK, the status code of a SXG file should be always 200, no other 20* response is expected.
Is it true? @twifkak

2020-12-19 14:03 UTC, orisano commented on .github/workflows/end-to-end-test.yml
> +      - name: check status code is must be 200
I fixed it

2020-12-19 14:36 UTC, kumagi requested changes

2020-12-19 14:36 UTC, kumagi commented on .github/workflows/end-to-end-test.yml
> +      - name: check status code to be 200
Capitalize please.

2020-12-19 14:43 UTC, kumagi commented
LGTM, thank you @orisano , I'll wait for respones of @twifkak until next working day.

2021-01-02 08:56 UTC, kumagi approved these changes

2021-01-06 02:21 UTC, orisano commented
what is status of this pr now?

2021-01-08 01:03 UTC, twifkak commented
Sorry for the delay; extended vacation. These changes seem good to me. Thank you for the test! I will merge.

I don't believe an "outer" response status of 200 is **required**, per the [loading spec](https://wicg.github.io/webpackage/loading.html#identifying-sxg), but I may be wrong. I would need to test to be certain.

However, 200 seems like the semantically correct choice (and certainly 000 is wrong).

2021-01-08 01:03 UTC, merged

2021-01-08 03:25 UTC, orisano commented
thanks! we are waiting for the next release.